spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20KB
      max-file-size: 200MB
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
media:
  file:
    upload:
      dir: /home/media/upload
